from __future__ import annotations

INTEGRATION_REGISTRY = {
    "wazuh": {
        "id": "wazuh",
        "name": "Wazuh",
        "description": "Receives alerts through webhook intake and can optionally pull recent alerts from Wazuh Indexer with credentials.",
        "category": "siem",
        "tools": ["ingest_wazuh_alert", "sync_wazuh_indexer_alerts", "test_wazuh_connection"],
        "fields": [
            {
                "key": "credential_name",
                "label": "Credential Name",
                "input": "text",
                "required": False,
                "sensitive": False,
                "advanced": False,
                "placeholder": "Production Wazuh",
                "help_text": "Friendly name for this connection, similar to an n8n credential.",
            },
            {
                "key": "connection_mode",
                "label": "Connection Mode",
                "input": "select",
                "required": True,
                "sensitive": False,
                "advanced": False,
                "help_text": "Choose how CyberRed should use this Wazuh credential.",
                "options": [
                    {"label": "Webhook only", "value": "webhook_only"},
                    {"label": "Indexer sync", "value": "indexer_sync"},
                    {"label": "Manager + Indexer", "value": "manager_and_indexer"},
                ],
            },
            {
                "key": "auth_type",
                "label": "Auth Type",
                "input": "select",
                "required": True,
                "sensitive": False,
                "advanced": False,
                "help_text": "MVP supports username/password basic auth for Wazuh APIs.",
                "options": [{"label": "Username / Password", "value": "basic"}],
            },
            {
                "key": "webhook_secret",
                "label": "Webhook Secret",
                "input": "password",
                "required": False,
                "sensitive": True,
                "advanced": False,
                "placeholder": "demo-wazuh-secret",
                "help_text": "Secret expected by the Wazuh alert intake webhook.",
            },
            {
                "key": "manager_url",
                "label": "API URL",
                "input": "text",
                "required": False,
                "sensitive": False,
                "advanced": False,
                "placeholder": "https://wazuh.example.local:55000",
                "help_text": "Wazuh server API base URL used for live connection tests.",
            },
            {
                "key": "api_username",
                "label": "API Username",
                "input": "text",
                "required": False,
                "sensitive": False,
                "advanced": False,
                "placeholder": "wazuh-wui",
                "help_text": "API username used to request a JWT from the Wazuh server API.",
            },
            {
                "key": "api_password",
                "label": "API Password",
                "input": "password",
                "required": False,
                "sensitive": True,
                "advanced": False,
                "placeholder": "",
                "help_text": "API password used to request a JWT from the Wazuh server API.",
            },
            {
                "key": "verify_tls",
                "label": "Verify TLS",
                "input": "checkbox",
                "required": False,
                "sensitive": False,
                "advanced": True,
                "help_text": "Disable only for self-signed lab environments.",
            },
            {
                "key": "indexer_url",
                "label": "Indexer URL",
                "input": "text",
                "required": False,
                "sensitive": False,
                "advanced": False,
                "placeholder": "https://wazuh-indexer.example.local:9200",
                "help_text": "Wazuh Indexer/OpenSearch URL used to pull recent alerts.",
            },
            {
                "key": "indexer_username",
                "label": "Indexer Username",
                "input": "text",
                "required": False,
                "sensitive": False,
                "advanced": False,
                "placeholder": "admin",
                "help_text": "Username for the Wazuh Indexer/OpenSearch API.",
            },
            {
                "key": "indexer_password",
                "label": "Indexer Password",
                "input": "password",
                "required": False,
                "sensitive": True,
                "advanced": False,
                "placeholder": "",
                "help_text": "Password for the Wazuh Indexer/OpenSearch API.",
            },
            {
                "key": "indexer_alert_index",
                "label": "Alert Index Pattern",
                "input": "text",
                "required": False,
                "sensitive": False,
                "advanced": True,
                "placeholder": "wazuh-alerts-*",
                "help_text": "Index pattern used when syncing recent Wazuh alerts.",
            },
        ],
    },
    "velociraptor": {
        "id": "velociraptor",
        "name": "Velociraptor",
        "description": "Executes host triage actions through mock or live artifact collection endpoints.",
        "category": "edr",
        "tools": ["run_process_triage", "run_autoruns_triage", "test_velociraptor_connection"],
        "fields": [
            {
                "key": "credential_name",
                "label": "Credential Name",
                "input": "text",
                "required": False,
                "sensitive": False,
                "advanced": False,
                "placeholder": "Production Velociraptor",
                "help_text": "Friendly name for this connection, similar to an n8n credential.",
            },
            {
                "key": "credential_type",
                "label": "Credential Type",
                "input": "select",
                "required": True,
                "sensitive": False,
                "advanced": False,
                "help_text": "Choose the Velociraptor credential workflow.",
                "options": [
                    {"label": "Mock demo", "value": "mock"},
                    {"label": "Live gRPC API", "value": "grpc_api"},
                    {"label": "HTTP adapter", "value": "http_adapter"},
                ],
            },
            {
                "key": "auth_type",
                "label": "Auth Type",
                "input": "select",
                "required": True,
                "sensitive": False,
                "advanced": False,
                "help_text": "gRPC uses api_client.yaml. HTTP adapter uses bearer token.",
                "options": [
                    {"label": "API client config", "value": "api_client_config"},
                    {"label": "Bearer token", "value": "bearer_token"},
                    {"label": "None / Mock", "value": "none"},
                ],
            },
            {
                "key": "mode",
                "label": "Mode",
                "input": "select",
                "required": True,
                "sensitive": False,
                "advanced": False,
                "options": [
                    {"label": "Mock", "value": "mock"},
                    {"label": "Live", "value": "live"},
                ],
                "help_text": "Use mock for demos or live to call a real Velociraptor deployment.",
            },
            {
                "key": "transport",
                "label": "Transport",
                "input": "select",
                "required": True,
                "sensitive": False,
                "advanced": False,
                "options": [
                    {"label": "gRPC API", "value": "grpc_api"},
                    {"label": "HTTP Adapter", "value": "http"},
                ],
                "help_text": "Recommended: gRPC API using an api_client config file.",
            },
            {
                "key": "api_client_config",
                "label": "API Client Config",
                "input": "text",
                "required": False,
                "sensitive": False,
                "advanced": False,
                "placeholder": "C:\\\\Velociraptor\\\\api_client.yaml",
                "help_text": "Path to the Velociraptor api_client YAML used by the gRPC CLI flow.",
            },
            {
                "key": "binary_path",
                "label": "Binary Path",
                "input": "text",
                "required": False,
                "sensitive": False,
                "advanced": True,
                "placeholder": "velociraptor",
                "help_text": "CLI used to run API queries. Usually velociraptor on PATH.",
            },
            {
                "key": "org_id",
                "label": "Org ID",
                "input": "text",
                "required": False,
                "sensitive": False,
                "advanced": True,
                "placeholder": "root",
                "help_text": "Velociraptor org to target for the collection.",
            },
            {
                "key": "timeout_seconds",
                "label": "Timeout Seconds",
                "input": "text",
                "required": False,
                "sensitive": False,
                "advanced": True,
                "placeholder": "120",
                "help_text": "Maximum time to wait for the flow to complete when using the gRPC API path.",
            },
            {
                "key": "base_url",
                "label": "Base URL",
                "input": "text",
                "required": False,
                "sensitive": False,
                "advanced": False,
                "placeholder": "https://velociraptor.example.local",
                "help_text": "Base URL for the optional HTTP adapter mode.",
            },
            {
                "key": "api_key",
                "label": "API Key",
                "input": "password",
                "required": False,
                "sensitive": True,
                "advanced": False,
                "placeholder": "",
                "help_text": "Bearer token used for the optional HTTP adapter mode.",
            },
            {
                "key": "run_path",
                "label": "Run Path",
                "input": "text",
                "required": True,
                "sensitive": False,
                "advanced": True,
                "placeholder": "/api/v1/collect",
                "help_text": "Relative path used when starting a collection flow.",
            },
            {
                "key": "status_path",
                "label": "Status Path",
                "input": "text",
                "required": True,
                "sensitive": False,
                "advanced": True,
                "placeholder": "/api/v1/flows/{flow_id}",
                "help_text": "Relative path used when polling a collection flow.",
            },
            {
                "key": "results_path",
                "label": "Results Path",
                "input": "text",
                "required": True,
                "sensitive": False,
                "advanced": True,
                "placeholder": "/api/v1/flows/{flow_id}/results",
                "help_text": "Relative path used when retrieving flow results.",
            },
            {
                "key": "verify_tls",
                "label": "Verify TLS",
                "input": "checkbox",
                "required": False,
                "sensitive": False,
                "advanced": True,
                "help_text": "Disable only for local lab or self-signed environments.",
            },
        ],
    },
}


TOOL_CATALOG = [
    {
        "id": "get_incident",
        "name": "Get Incident",
        "access": "read",
        "description": "Retrieve a single incident with alerts, evidence, and timeline.",
    },
    {
        "id": "list_incident_evidence",
        "name": "List Incident Evidence",
        "access": "read",
        "description": "Return evidence records linked to an incident.",
    },
    {
        "id": "summarize_incident",
        "name": "Summarize Incident",
        "access": "read",
        "description": "Generate a concise deterministic summary for an incident.",
    },
    {
        "id": "request_host_triage",
        "name": "Request Host Triage",
        "access": "write",
        "description": "Prepare a triage action that must be explicitly confirmed before execution.",
    },
]


POLICY_CATALOG = [
    {
        "id": "read_auto_execute",
        "name": "Read Actions Execute Immediately",
        "scope": "read",
        "description": "Read-only incident, evidence, and summary operations run immediately.",
    },
    {
        "id": "write_requires_confirmation",
        "name": "Write Actions Require Confirmation",
        "scope": "write",
        "description": "Triage requests are stored as pending actions and need explicit confirmation in the UI.",
    },
]
